# Generated by Django 4.2 on 2023-05-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_recom_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='book_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
