# Generated by Django 4.2 on 2023-09-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_recom_main', '0003_book_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default=123, max_length=13, unique=True),
        ),
    ]
